# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: Zadok the Priest
# Can be used to add a meta tag to the HTML header
site_author: "Nathan @nazzacode Sharp"

nav:
  - "Home": index.md
  - "About": about.md
  - "Blog":
      - blog/index.md
      - "Why XR computing is The Future of Work™": blog/why_XR_computing_is_the_future_of_work.md
      - "Does XR need a new keyboard?": blog/does_XR_need_a_new_keyboard.md
  - "Tags": tags.md
  - "Memes": memes.md

theme:
  name: material
  custom_dir: overrides
  icon:
    logo: material/safety-goggles
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
      primary: grey
      accent: grey
      # primary: blue grey
      # accent: light blue
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to light mode
      primary: grey
      accent: grey
  font: # set some nicer custom fonts! (latex/futuristic)
    text: Jura
    code: DM Mono
    # To try
    # IBM plex mono
    # Josefin Slab regular
    # Computer Modern
    #
  features:
    - navigation.expand
    - navigation.indexes
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.top # 'back to top' button
    - navigation.tracking
    - toc.follow

plugins:
  - search
  - tags:
      tags_file: tags.md
  # - git-revision-date

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.snippets:
      auto_append:
        - includes/glossary.md
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - toc:
      permalink: §

extra:
  generator: false
  social:
    - icon: fontawesome/regular/envelope
      link: mailto:nathansharp03@gmail.com
    - icon: fontawesome/brands/github
      link: https://github.com/nazzacode
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/nazzasharp

extra_css:
  - stylesheets/extra.css
  - docs/css/mkdocs-material-themes/onedark_colors.css
  # - css/mkdocs-material-themes/gruvbox_colors.css
  # - docs/css/mkdocs-material-themes/material_theme.css

extra_javascript:
  - javascript/extra.js
